development:
  adapter: postgresql
  encoding: utf8
  database: fast_food_dev
  pool: 5
  username: postgres
  password: vlqkdu

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: postgres
  password: vlqkdu

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: postgres
  password: vlqkdu